spring:
  application:
    name: registry-server
  banner:
    location: classpath:banner.txt
  main:
    banner-mode: console
server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
