{
 "title": "Meli Challenge -  Dashboard",
 "time": { "from": "2025-09-29T11:52:33.091Z", "to": "2025-09-29T12:22:33.091Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Status 400 - 499",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{status=~\"4..\"}) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Status 500 - 599",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{status=~\"5..\"}) by (uri,method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Status 200 - 299",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(http_server_requests_seconds_count{status=~\"2..\", uri!~\"/actuator.*\"}) by (uri)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GET /product-detail/detail/{ProductId} (Cantidad)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "product_detail_getProductDetailByProductId_seconds_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GET /product-detail/detail/{ProductId} (Tiempo de respuesta)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "product_detail_getProductDetailByProductId_seconds_sum",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso total de CPU del sistema",
   "type": "timeseries",
   "description": "La métrica system.cpu.usage en Spring Boot Actuator indica el uso reciente de CPU a nivel de sistema, es decir, cuánto del tiempo total de CPU está siendo utilizado por todos los procesos del sistema operativo, no solo por tu aplicación Java.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    { "expr": "system_cpu_usage * 100", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Disco Duro(GB)",
   "type": "timeseries",
   "description": "La métrica  indica la cantidad de espacio libre en disco, expresada en bytes, disponible en el sistema donde corre tu aplicación Spring Boot. Es útil para monitorear la capacidad de almacenamiento y prevenir fallos por falta de espacio.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    { "expr": "disk_free_bytes/1000000000", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Tiempo de Arranque (App)",
   "type": "timeseries",
   "description": "La métrica application_ready_time_seconds indica cuánto tiempo tarda tu aplicación Spring Boot en estar completamente lista para recibir solicitudes, desde el momento en que se inicia hasta que se publica el evento ApplicationReadyEvent.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    { "expr": "application_ready_time_seconds", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Hilos de ejecución activos",
   "type": "timeseries",
   "description": "La métrica tomcat.threads.current (también conocida como tomcat_threads_current_threads en algunos sistemas de monitoreo) indica el número total de hilos activos en el pool de ejecución de Tomcat en ese momento. Es una métrica clave para entender la capacidad de procesamiento concurrente de tu servidor embebido Tomcat en una aplicación Spring Boot.\n\n",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    { "expr": "tomcat_threads_current_threads", "legendFormat": "__auto" }
   ]
  }
 ]
}